name: "Accuknox SAST: Opengrep"
description: "Run AccuKnox SAST scan on the repository; results are uploaded and severity-based fail is enforced."

branding:
  icon: "shield"
  color: "purple"

inputs:
  severity:
    description: "Fail pipeline if a finding matches this severity (comma-separated, e.g., CRITICAL,HIGH)"
    required: false
    default: "CRITICAL"
  pipeline_id:
    description: "Pipeline/Job ID"
    required: false
    default: ${{ github.run_id }}
  job_url:
    description: "CI job URL"
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  accuknox_endpoint:
    description: "CSPM panel endpoint URL"
    required: true
  accuknox_token:
    description: "Token for CSPM"
    required: true
  accuknox_label:
    description: "Label in AccuKnox SaaS"
    required: true
  accuknox_ai_analysis:
    description: "Enable AI analysis"
    required: false
    default: "false"
  anthropic_api_key:
    description: "Anthropic API key"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox SAST Scan
      shell: bash
      env:
        PIPELINE_ID: ${{ inputs.pipeline_id }}
        JOB_URL: ${{ inputs.job_url }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_AI_ANALYSIS: ${{ inputs.accuknox_ai_analysis }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
      run: |
        # Download scanner
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        echo "Running SAST scan..."
        ./accuknox-aspm-scanner scan sast \
          --command "." \
          --repo-url "https://github.com/${GITHUB_REPOSITORY}.git" \
          --commit-ref "${GITHUB_REF#refs/heads/}" \
          --commit-sha "${GITHUB_SHA}" \
          --pipeline-id "$PIPELINE_ID" \
          --job-url "$JOB_URL" \
          --container-mode \
          $( [ "${ACCUKNOX_AI_ANALYSIS}" = "true" ] && echo "--ai-analysis --anthropic-api-key=$ANTHROPIC_API_KEY" )

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: sast-scan-results
        path: results.json
        retention-days: 30

    - name: Fail if severity found
      shell: bash
      env:
        SEVERITY_LIST: ${{ inputs.severity }}
      run: |
        echo "Checking results.json for severities: $SEVERITY_LIST"
        if [ ! -f results.json ]; then
          echo "ERROR: results.json not found!"
          exit 1
        fi

        FOUND=$(jq -r '.results[]?.extra.severity // empty | ascii_upcase' results.json | grep -E "$(echo $SEVERITY_LIST | tr ',' '|')")

        if [ -n "$FOUND" ]; then
          echo "Pipeline failed due to finding(s) with severity: $FOUND"
          exit 1
        else
          echo "No matching severity findings found."
        fi
