name: "Accuknox SAST: Opengrep"
description: "Run AccuKnox SAST scan on the repository; results are automatically uploaded to CSPM panel."

branding:
  icon: "shield"
  color: "purple"

inputs:
  severity:
    description: "Fail the pipeline if scan finds this severity (LOW, MEDIUM, HIGH, CRITICAL)"
    required: false
    default: "CRITICAL"
  soft_fail:
    description: "Do not fail the pipeline if scan finds issues"
    required: false
    default: "false"
  pipeline_id:
    description: "Pipeline/Job ID to correlate with CI/CD runs"
    required: false
    default: ${{ github.run_id }}
  job_url:
    description: "URL for the current GitHub job"
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  accuknox_endpoint:
    description: "CSPM panel endpoint URL"
    required: true
  accuknox_token:
    description: "Token for authenticating with CSPM panel"
    required: true
  accuknox_label:
    description: "Label in AccuKnox SaaS for scan results"
    required: true
  accuknox_ai_analysis:
    description: "Enable AI analysis"
    required: false
    default: "false"
  anthropic_api_key:
    description: "Anthropic API key for AI analysis"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox SAST Scan
      shell: bash
      env:
        SEVERITY: ${{ inputs.severity }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        PIPELINE_ID: ${{ inputs.pipeline_id }}
        JOB_URL: ${{ inputs.job_url }}
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_AI_ANALYSIS: ${{ inputs.accuknox_ai_analysis }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
      run: |
        # Validate required secrets
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$ACCUKNOX_LABEL" ]; then
          echo "ERROR: ACCUKNOX_ENDPOINT, ACCUKNOX_TOKEN, and ACCUKNOX_LABEL must be set!"
          exit 1
        fi

        # Download latest ASPM Scanner
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        # Determine soft-fail argument
        SOFT_FAIL_ARG=""
        SOFT_FAIL="${SOFT_FAIL//[$'\t\r\n ']}"  # clean whitespace
        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        # Build AI analysis arguments
        AI_ARGS=""
        if [ "$ACCUKNOX_AI_ANALYSIS" = "true" ]; then
          AI_ARGS="--ai-analysis"
          if [ -n "$ANTHROPIC_API_KEY" ]; then
            AI_ARGS="$AI_ARGS --anthropic-api-key=$ANTHROPIC_API_KEY"
          else
            echo "WARNING: AI analysis enabled but ANTHROPIC_API_KEY not provided"
          fi
        fi

        # Build severity argument
        SEVERITY_ARG=""
        if [ -n "$SEVERITY" ]; then
          SEVERITY_ARG="--severity $SEVERITY"
        fi

        # Run SAST scan (OpenGrep) with severity
        echo "Running AccuKnox SAST scan..."
        ./accuknox-aspm-scanner scan --keep-results $SOFT_FAIL_ARG sast \
          --command "." \
          --repo-url "https://github.com/${GITHUB_REPOSITORY}.git" \
          --commit-ref "${GITHUB_REF#refs/heads/}" \
          --commit-sha "${GITHUB_SHA}" \
          --pipeline-id "$PIPELINE_ID" \
          --job-url "$JOB_URL" \
          --container-mode \
          $SEVERITY_ARG \
          $AI_ARGS
